version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: impcourse_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: impcourse_db
      MYSQL_USER: gustavo
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - impcourse_network

volumes:
  mysql_data:

networks:
  impcourse_network:
    driver: bridge
